version: '2'

services:
  db:
    image: postgres:10
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=presupuestos
      - POSTGRES_USER=presupuestos
      - POSTGRES_PASSWORD=presupuestos
    ports:
      - "0.0.0.0:5432:5432"

volumes:
  db-data:

