DROP TABLE IF EXISTS parlamento_chap."Anexo de Inversiones";

CREATE TABLE  parlamento_chap."Anexo de Inversiones" (
  "CODSEC" VARCHAR(255),
  "CLAFUN" VARCHAR(255),
  "CODSER" VARCHAR(255),
  "CLAART" VARCHAR(255),
  "CODPRO" VARCHAR(255),
  "MEDIDA" VARCHAR(255),
  "CODPROV" VARCHAR(255),
  "DENOM" VARCHAR(255),
  "IMPORTE" DOUBLE PRECISION NULL
);

DROP TABLE IF EXISTS parlamento_chap."Aplicaciones";

CREATE TABLE  parlamento_chap."Aplicaciones" (
  "Codsec" VARCHAR(255),
  "Clafun" VARCHAR(255),
  "Codser" VARCHAR(255),
  "Claeco" VARCHAR(255),
  "Codpro" VARCHAR(255),
  "Medida" VARCHAR(255),
  "Denom" VARCHAR(255),
  "Importe" DOUBLE PRECISION NULL
);

DROP TABLE IF EXISTS parlamento_chap."ENMIENDAS";

CREATE TABLE  parlamento_chap."ENMIENDAS" (
  "TIPPRE" VARCHAR(1),
  "NUM_ENMIEN" INTEGER,
  "GRUPO" VARCHAR(10) NOT NULL,
  "TIPO_ENMIENDA" VARCHAR(1),
  "APLICACION" VARCHAR(16) NOT NULL,
  "PROYECTO" VARCHAR(10) NOT NULL,
  "IMPORTE" DOUBLE PRECISION NULL,
  "T_ENMIENDA" TEXT,
  "T_JUSTIFICACION" TEXT,
  "PESO" SMALLINT,
  "SECCION" VARCHAR(5),
  "DENOMINACION" VARCHAR(140),
  "IMPORTE_HACIENDA" DOUBLE PRECISION NULL,
  "SERVICIO" VARCHAR(2)
);

DROP TABLE IF EXISTS parlamento_chap."GASTOS";

CREATE TABLE  parlamento_chap."GASTOS" (
  "DISTINTIVO" VARCHAR(1),
  "TIPPRE" VARCHAR(1),
  "APLICACION" VARCHAR(16),
  "PROYECTO" VARCHAR(10),
  "MEDIDA" VARCHAR(15),
  "SECCION" VARCHAR(5),
  "PROGRAMA" VARCHAR(3),
  "SERVICIO" VARCHAR(2),
  "APLIECO" VARCHAR(6),
  "CONCEPTO" VARCHAR(3),
  "ARTICULO" VARCHAR(2),
  "CAPITULO" VARCHAR(1),
  "PROVINCIA" VARCHAR(2),
  "DENOMINACION" VARCHAR(140),
  "IMPORTE" DOUBLE PRECISION NULL
);

DROP TABLE IF EXISTS parlamento_chap."GGPP";

CREATE TABLE  parlamento_chap."GGPP" (
  "GRUPO" VARCHAR(10) NOT NULL,
  "DESCRIPCION_GRUPO" VARCHAR(100),
  "PESO" VARCHAR(1),
  "ACTIVO" BOOLEAN,
  "GRUPO_NOMBRE_ENMIENDA" VARCHAR(20)
);

DROP TABLE IF EXISTS parlamento_chap."Grupo_Indices";

CREATE TABLE  parlamento_chap."Grupo_Indices" (
  "GRUPO" VARCHAR(10) NOT NULL,
  "DESCRIPCION GRUPO" VARCHAR(50)
);

DROP TABLE IF EXISTS parlamento_chap."INGRESOS";

CREATE TABLE  parlamento_chap."INGRESOS" (
  "DISTINTIVO" VARCHAR(1),
  "TIPPRE" VARCHAR(1),
  "APLICACION" VARCHAR(16),
  "PROYECTO" VARCHAR(10),
  "MEDIDA" VARCHAR(15),
  "SECCION" VARCHAR(5),
  "SERVICIO" VARCHAR(2),
  "PROGRAMA" VARCHAR(3),
  "APLIECO" VARCHAR(6),
  "CONCEPTO" VARCHAR(3),
  "ARTICULO" VARCHAR(2),
  "CAPITULO" VARCHAR(1),
  "PROVINCIA" VARCHAR(2),
  "DENOMINACION" VARCHAR(140),
  "IMPORTE" DOUBLE PRECISION NULL
);

DROP TABLE IF EXISTS parlamento_chap."nProgramas";

CREATE TABLE  parlamento_chap."nProgramas" (
  "Año" DOUBLE PRECISION NULL,
  "CFun" VARCHAR(255),
  "CFunDenom" VARCHAR(255),
  "CFunDenomlarga" VARCHAR(255)
);

DROP TABLE IF EXISTS parlamento_chap."nProgramas-Plus";

CREATE TABLE  parlamento_chap."nProgramas-Plus" (
  "CFun" VARCHAR(255),
  "CFunDenom" VARCHAR(255),
  "CFunDenomlarga" VARCHAR(255)
);


DROP TABLE IF EXISTS parlamento_chap."nSecciones";

CREATE TABLE  parlamento_chap."nSecciones" (
  "CodSec" VARCHAR(255),
  "SeccDen" VARCHAR(255),
  "SeccDenom" VARCHAR(255)
);


DROP TABLE IF EXISTS parlamento_chap."nServicios";

CREATE TABLE  parlamento_chap."nServicios" (
  "Año" DOUBLE PRECISION NULL,
  "Seccion" VARCHAR(255),
  "Servicio" VARCHAR(255),
  "ServDeno" VARCHAR(255),
  "ServDenomlarga" VARCHAR(255)
);


DROP TABLE IF EXISTS parlamento_chap."PROYECTOSDELEY";

CREATE TABLE  parlamento_chap."PROYECTOSDELEY" (
  "anio" INTEGER NOT NULL,
  "proyectodeley" VARCHAR(50),
  "activo" BOOLEAN
);


DROP TABLE IF EXISTS parlamento_chap."RELACIONES";

CREATE TABLE  parlamento_chap."RELACIONES" (
  "TIPPRE" VARCHAR(1),
  "NUM_ENMIEN" INTEGER,
  "GRUPO" VARCHAR(10) NOT NULL,
  "APLICACION" VARCHAR(16) NOT NULL,
  "PROYECTO" VARCHAR(10) NOT NULL,
  "R_APLICACION" VARCHAR(16) NOT NULL,
  "R_PROYECTO" VARCHAR(10) NOT NULL,
  "IMPORTE" DOUBLE PRECISION NOT NULL,
  "DENOMINACION" VARCHAR(140),
  "IMPORTE_HACIENDA" DOUBLE PRECISION NULL,
  "SERVICIO" VARCHAR(2),
  "R_SERVICIO" VARCHAR(2)
);


DROP TABLE IF EXISTS parlamento_chap."RELACIONES_REDISTRIB_MODIF_DESC";

CREATE TABLE  parlamento_chap."RELACIONES_REDISTRIB_MODIF_DESC" (
  "NUM_ENMIEN" INTEGER,
  "GRUPO" VARCHAR(10) NOT NULL,
  "APLICACION" VARCHAR(16) NOT NULL,
  "PROYECTO" VARCHAR(10) NOT NULL,
  "ORDEN" INTEGER NOT NULL,
  "NUEVO_TEXTO" VARCHAR(255),
  "IMPORTE" DOUBLE PRECISION NULL
);


DROP TABLE IF EXISTS parlamento_chap."SECCIONES";

CREATE TABLE  parlamento_chap."SECCIONES" (
  "CodSec" VARCHAR(255),
  "SeccDen" VARCHAR(255),
  "SeccDenom" VARCHAR(255)
);


DROP TABLE IF EXISTS parlamento_chap."Tipos de Enmienda";

CREATE TABLE  parlamento_chap."Tipos de Enmienda" (
  "TIPOENMIENDA" VARCHAR(1) NOT NULL,
  "DESCRIPCION_OCP" VARCHAR(50),
  "DESCRIPCION_BOPA" VARCHAR(50),
  "DESCRIPCION_INFORME" VARCHAR(50)
);