/*
  Carga de variables
*/
DEF TABLESPACE_D='TS_TREWA'
DEF DATAFILE_D='/u01/app/oracle/TS_TREWA.dbf'
DEF DATAFILESIZE_D='500'
DEF TABLESPACE_I='TS_TREWA_I'
DEF DATAFILE_I='/u01/app/oracle/TS_TREWA_I.dbf'
DEF DATAFILESIZE_I='500'
DEF TABLESPACE_B='TS_TREWA_BLOB'
DEF DATAFILE_B='/u01/app/oracle/TS_TREWA_BLOB.dbf'
DEF DATAFILESIZE_B='500'



/*
  Creacion Tablespaces
*/
CREATE TABLESPACE "&TABLESPACE_D" 
    LOGGING
        DATAFILE '&DATAFILE_D' SIZE &DATAFILESIZE_D M 
        AUTOEXTEND ON
        ONLINE
        PERMANENT
        EXTENT MANAGEMENT LOCAL 
        AUTOALLOCATE
        BLOCKSIZE 8K
        SEGMENT SPACE MANAGEMENT AUTO 
        FLASHBACK ON;

CREATE TABLESPACE "&TABLESPACE_I" 
    LOGGING
        DATAFILE '&DATAFILE_I' SIZE &DATAFILESIZE_I M 
        AUTOEXTEND ON
        ONLINE
        PERMANENT
        EXTENT MANAGEMENT LOCAL 
        AUTOALLOCATE
        BLOCKSIZE 8K
        SEGMENT SPACE MANAGEMENT AUTO 
        FLASHBACK ON;

CREATE TABLESPACE "&TABLESPACE_B" 
    LOGGING
        DATAFILE '&DATAFILE_B' SIZE &DATAFILESIZE_B M 
        AUTOEXTEND ON
        ONLINE
        PERMANENT
        EXTENT MANAGEMENT LOCAL 
        AUTOALLOCATE
        BLOCKSIZE 8K
        SEGMENT SPACE MANAGEMENT AUTO 
        FLASHBACK ON;
	

COMMIT;

