
--Ejemplo de creación de usuario:
/*
  Carga de variables
*/
DEF TABLESPACE_D='TS_TREWA'
DEF DATAFILESIZE_D='500'
DEF TABLESPACE_I='TS_TREWA_I'
DEF DATAFILESIZE_I='500'
DEF TABLESPACE_B='TS_TREWA_BLOB'
DEF DATAFILESIZE_B='500'
DEF USU_ADMIN='TREWA'
DEF PASSWORD_USU_ADMIN='TREWA'



CREATE USER "&USU_ADMIN"
IDENTIFIED BY "&PASSWORD_USU_ADMIN"
DEFAULT TABLESPACE "&TABLESPACE_D"
PROFILE DEFAULT
ACCOUNT UNLOCK
QUOTA UNLIMITED ON "&TABLESPACE_D"
QUOTA UNLIMITED ON "&TABLESPACE_I"
QUOTA UNLIMITED ON "&TABLESPACE_B";
GRANT     ALTER ANY TABLE TO "&USU_ADMIN";
GRANT     CREATE ANY SEQUENCE TO "&USU_ADMIN";
GRANT     CREATE ANY TABLE TO "&USU_ADMIN";
GRANT     CREATE PUBLIC SYNONYM TO "&USU_ADMIN";
GRANT     CREATE ANY TRIGGER TO "&USU_ADMIN";
GRANT     CREATE ANY VIEW TO "&USU_ADMIN";
GRANT     DROP PUBLIC SYNONYM TO "&USU_ADMIN";
GRANT     DROP ANY SEQUENCE TO "&USU_ADMIN";
GRANT     DROP ANY TABLE TO "&USU_ADMIN";
GRANT     CREATE ROLE TO "&USU_ADMIN";
GRANT     DROP ANY ROLE TO "&USU_ADMIN";
GRANT     ALTER ANY ROLE TO "&USU_ADMIN";
GRANT     "RESOURCE" TO "&USU_ADMIN";
GRANT     "CONNECT" TO "&USU_ADMIN";

COMMIT;

--(Sólo si se trabaja con roles de base de datos-->) GRANT SELECT ON  "SYS"."DBA_ROLE_PRIVS" TO "TREWA";

--(NOTA: téngase en cuenta que se puede dar el role de CONNECT donde van implícitos: create view, table, sequence, etc.)
