DEF OWNER='TREWA'

Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '11', 
    'CÁDIZ', 'CÁDIZ', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '14', 
    'CÓRDOBA', 'CÓRDOBA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '18', 
    'GRANADA', 'GRANADA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '21', 
    'HUELVA', 'HUELVA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '23', 
    'JAÉN', 'JAÉN', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '29', 
    'MALAGA', 'MÁLAGA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '41', 
    'SEVILLA', 'SEVILLA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '04', 
    'ALMERÍA', 'ALMERÍA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '01', 
    'ALAVA', 'ALAVA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '02', 
    'ALBACETE', 'ALBACETE', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '03', 
    'ALICANTE', 'ALICANTE', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '05', 
    'AVILA', 'AVILA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '06', 
    'BADAJOZ', 'BADAJOZ', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '07', 
    'BALEARES', 'BALEARES', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '08', 
    'BARCELONA', 'BARCELONA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '09', 
    'BURGOS', 'BURGOS', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '10', 
    'CACERES', 'CACERES', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '12', 
    'CASTELLON', 'CASTELLON', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '51', 
    'CEUTA', 'CEUTA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '13', 
    'CIUDAD REAL', 'CIUDAD REAL', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '15', 
    'CORUÑA (LA)', 'CORUÑA (LA)', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '16', 
    'CUENCA', 'CUENCA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '17', 
    'GERONA', 'GERONA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '19', 
    'GUADALAJARA', 'GUADALAJARA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '20', 
    'GUIPUZCOA', 'GUIPUZCOA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '22', 
    'HUESCA', 'HUESCA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '24', 
    'LEON', 'LEON', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '25', 
    'LERIDA', 'LERIDA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '27', 
    'LUGO', 'LUGO', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '28', 
    'MADRID', 'MADRID', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '52', 
    'MELILLA', 'MELILLA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '30', 
    'MURCIA', 'MURCIA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '31', 
    'NAVARRA', 'NAVARRA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '32', 
    'ORENSE', 'ORENSE', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '33', 
    'ASTURIAS', 'ASTURIAS', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '34', 
    'PALENCIA', 'PALENCIA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '35', 
    'PALMAS (LAS)', 'PALMAS (LAS)', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '36', 
    'PONTEVEDRA', 'PONTEVEDRA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '26', 
    'RIOJA (LA)', 'RIOJA (LA)', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '37', 
    'SALAMANCA', 'SALAMANCA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '39', 
    'CANTABRIA', 'CANTABRIA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '40', 
    'SEGOVIA', 'SEGOVIA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '42', 
    'SORIA', 'SORIA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '43', 
    'TARRAGONA', 'TARRAGONA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '38', 
    'SANTA CRUZ DE TENERIFE', 'SANTA CRUZ DE TENERIFE', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '44', 
    'TERUEL', 'TERUEL', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '45', 
    'TOLEDO', 'TOLEDO', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '46', 
    'VALENCIA', 'VALENCIA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '47', 
    'VALLADOLID', 'VALLADOLID', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '48', 
    'VIZCAYA', 'VIZCAYA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '49', 
    'ZAMORA', 'ZAMORA', '-', '-');
Insert into &OWNER..GN_PROVINCIAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_PROVINCIA, 
    S_PROVINCIA, D_PROVINCIA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, '50', 
    'ZARAGOZA', 'ZARAGOZA', '-', '-');
COMMIT;
