DEF OWNER='TREWA'

Insert into &OWNER..GN_UNI_ORG
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_UORG, 
    C_UNI_ORG, S_UNI_ORG, D_UNI_ORG, V_TIPO, MUNI_C_MUNICIPIO, 
    PROV_C_PROVINCIA, TIVA_C_TIPO_VIA, T_NOMBRE_VIA, N_NUMERO, T_LETRA, 
    T_ESCALERA, N_PISO, T_PUERTA, C_POSTAL, T_TELEFONO, 
    T_TLFMOVIL, T_FAX, T_EMAIL, C_CIWA, T_ID_ARIES, 
    T_IDENTIFICADOR, T_DIGITO_CONTROL, F_INI_VIG, F_FIN_VIG, UORG_X_UORG, 
    TIOR_X_TIOR, TORZ_C_TIPO_ORGZ, C_PRELACION, CREADO_API, MODIFICADO_API, 
    C_DIR3)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'CEHAP', 'Consej. Economía, Hacienda y Admón. Púb.', 'Consejería de Economía, Hacienda y Administración Pública', 'SC', '091', 
    '41', NULL, NULL, NULL, NULL, 
    NULL, 1, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, '-', '-', 
    NULL);

COMMIT;