DEF OWNER='TREWA'

Insert into &OWNER..TR_TIPOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TICO, 
    C_ABREVIATURA, D_TIPO_COMP, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'TREW@', 'COMPONENTES DE TRAMITACIÓN', 'N', 1, '-', 
    '-');
Insert into &OWNER..TR_TIPOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TICO, 
    C_ABREVIATURA, D_TIPO_COMP, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    'W@RDA', 'COMPONENTES DE ALMACENAMIENTO DE DOCUMENTOS', 'N', 2, '-', 
    '-');
Insert into &OWNER..TR_TIPOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TICO, 
    C_ABREVIATURA, D_TIPO_COMP, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    '@RCHIVA', 'COMPONENTES DE ARCHIVO DE EXPEDIENTES Y DOCUMENTOS', 'N', 3, '-', 
    '-');
Insert into &OWNER..TR_TIPOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TICO, 
    C_ABREVIATURA, D_TIPO_COMP, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    'BUS', 'BUS DE CONEXIÓN', 'N', 4, '-', 
    '-');
Insert into &OWNER..TR_TIPOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TICO, 
    C_ABREVIATURA, D_TIPO_COMP, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 5, 
    'TDC', 'TRAYECTORIA DIGITAL DE LA CIUDADANÍA', 'N', 5, '-', 
    '-');
COMMIT;