DEF OWNER='TREWA'


Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'TREWA', 'TREWA', 1, 1, NULL, 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    'W@RDA', 'COMPONENTE W@RDA', 2, 1, 'NOMBRE_SERVIDOR', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    'WEBOFFICE', 'COMPONENTE WEBOFFICE', 1, 1, NULL, 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    '@VISADOR', 'COMPONENTE @VISADOR', 1, 1, 'NOMBRE_SERVIDOR', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 5, 
    'NOTIFIC@', 'COMPONENTE TREW@ DE NOTIFICACIONES', 1, 1, 'ws031.juntadeandalucia.es', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 6, 
    'PORT@FIRMAS', 'COMPONENTE PORT@FIRMAS', 1, 1, '7.128.80.19', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 7, 
    'BUS', 'BUS DE CONEXIÓN W@NDA', 4, 1, 'NOMBRE_SERVIDOR', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 8, 
    'ALFRESCO', 'COMPONENTE DE ALMACENAMIENTO DE DOCUMENTOS', 2, 1, 'NOMBRE_SERVIDOR', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 9, 
    '@FIRMA', 'COMPONENTE @FIRMA PARA FIRMAR DOCUMENTOS', 1, 1, 'ws028.juntadeandalucia.es', 
    'ptwanda', 'pt4561wanda', NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 10, 
    'NumeradorPT', 'Numerador para PTw@ndA', 1, 1, NULL, 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_COMPONENTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_COMP, 
    C_NOMBRE, D_DESCRIPCION, TICO_X_TICO, UORG_X_UORG, T_DIRECCION_IP, 
    T_USUARIO, T_PASSWORD, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 11, 
    'HCV', 'Herramienta centralizada de verificación', 1, 1, NULL, 
    NULL, NULL, NULL, '-', '-');   
	
COMMIT;
