DEF OWNER="TREWA"

Insert into &OWNER..GN_SISTEMAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_STMA, 
    C_SISTEMA, D_SISTEMA, V_CONEX_BUS, COMP_X_COMP_INF, COMP_X_COMP_AVI, 
    COMP_X_COMP_GUAR, COMP_X_COMP_ARCH, COMP_X_COMP_REG, COMP_X_COMP_FIRMA, COMP_X_COMP_NOTI, 
    CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'TREWA', 'MOTOR DE TRAMITACIÓN TREW@', 'N', 1, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    '-', '-');

COMMIT;
