DEF OWNER="TREWA"

Insert into &OWNER..GN_TIPOS_IDENTIFICADOR
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_ABREVIATURA, 
    D_TIPO_IDENT, V_TIPO_IDENT, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'NIF', 
    'NIF', 'F', 'N', NULL, '-', 
    '-');
Insert into &OWNER..GN_TIPOS_IDENTIFICADOR
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_ABREVIATURA, 
    D_TIPO_IDENT, V_TIPO_IDENT, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'NIE', 
    'NIE', 'F', 'N', NULL, '-', 
    '-');
Insert into &OWNER..GN_TIPOS_IDENTIFICADOR
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_ABREVIATURA, 
    D_TIPO_IDENT, V_TIPO_IDENT, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CIF', 
    'CIF', 'J', 'N', NULL, '-', 
    '-');	
	
COMMIT;
