DEF OWNER="TREWA"

Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'ENT. REG.', 'ENTIDADES REGISTRALES', 'N', 'R', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    'PODER JUD.', 'PODER JUDICIAL', 'N', 'J', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    'COM. AUT.', 'COMUNIDADES AUTÓNOMAS', 'N', 'A', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    'ENT. LOC.', 'ENTIDADES LOCALES', 'N', 'L', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 5, 
    'DIP./CONS.', 'DIPUTACIONES Y CONSEJOS Y CABILDOS INSULARES', 'N', 'D', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 6, 
    'PROPIOS', 'PROPIOS', 'N', 'O', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 7, 
    'UE', 'UNIÓN EUROPEA', 'N', 'U', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 8, 
    'JEF. EST.', 'JEFATURA DEL ESTADO', 'N', 'F', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 9, 
    'TRIB. CON.', 'TRIBUNAL CONSTITUCIONAL', 'N', 'T', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 10, 
    'PODER EJE.', 'PODER EJECUTIVO', 'N', 'E', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 11, 
    'PODER LEG.', 'PODER LEGISLATIVO', 'N', 'C', '-', 
    '-');
Insert into &OWNER..GN_TIPOS_ORGANISMO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIOR, 
    C_ABREVIATURA, D_TIPO_ORGANISMO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 12, 
    'IDEA', 'ENTIDADES Y ORGANISMOS ADSCRITOS', 'N', '-', '-', 
    '-');    
COMMIT;
