DEF OWNER="TREWA"

Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20113, 
    'NO EXISTE EL TIPO DE CONTACTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20114, 
    'NO EXISTE NINGUNA RELACIÓN ENTRE LOS EXPEDIENTES', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20115, 
    'NO SE HA PODIDO INSERTAR O MODIFICAR LA RELACIÓN ENTRE LOS INTERESADOS YA QUE LA NUEVA RELACION YA EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20116, 
    'NO EXISTE NINGUNA RELACIÓN ENTRE LOS INTERESADOS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20117, 
    'NO EXISTE EL COMPONENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20118, 
    'FALTAN DATOS REFERENTE AL EXPEDIENTE EXTERNO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20119, 
    'NO SE HA PODIDO INSERTAR O MODIFICAR LA RELACION ENTRE LOS EXPEDIENTES', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20120, 
    'NO EXISTE EL USUARIO ASIGNADO AL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20121, 
    'NO SE HA PODIDO INSERTAR LA NOTIFICACION DEL INTERESADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20122, 
    'NO EXISTE LA NOTIFICACIÓN, O NO SE HA PODIDO MODIFICAR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20123, 
    'NO EXISTE EL USUARIO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20124, 
    'NO SE PUEDE TRAMITAR. SE HA SUPERADO EL NÚMERO MÁXIMO DE VECES QUE SE PUEDE PRODUCIR ESTE CAMBIO DE FASE PARA EL EXPEDIENTE.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20125, 
    'NO SE PUEDE REALIZAR LA ACCION. EL PROCEDIMIENTO ESTÁ BLOQUEADO POR UN USUARIO ADMINISTRADOR EN ESTOS MOMENTOS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20126, 
    'ALGUNO DE LOS PARÁMETROS NO ES CORRECTO O NO SE HA INDICADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20127, 
    'ESTA FUNCIONALIDAD NO ESTÁ DISPONIBLE.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20128, 
    'EL BLOQUE PERMITIDO NO ES CORRECTO O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20129, 
    'ERROR GENÉRICO DE SERVICIO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20130, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE EL EXPEDIENTE.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20131, 
    'NO EXISTE EL DATO DE CONTACTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20132, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE EL EXPEDIENTE, ESTÁ ARCHIVADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20133, 
    'EL TIPO DE DOCUMENTO NO ES NOTIFICABLE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20134, 
    'NO SE HA PODIDO ASIGNAR EL USUARIO AL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20135, 
    'NO SE HA PODIDO MODIFICAR EL USUARIO ASIGNADO AL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20136, 
    'NO SE HA PODIDO ELIMINAR EL USUARIO ASIGNADO AL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20446, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE EL EXPEDIENTE, LA OPCIÓN DE ARCHIVO ES TELEMÁTICA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20447, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE EL EXPEDIENTE, LA OPCIÓN DE ARCHIVO NO ES TELEMÁTICA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20448, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE EL EXPEDIENTE, NO EXISTE PETICIÓN TELEMÁTICA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20430, 
    'SOLO SE PUEDEN INSERTAR 3 ENVÍOS COMO MÁXIMO PARA UNA NOTIFICACIÓN. SE HA SOBREPASAO EL MÁXIMO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20431, 
    'NO SE PUEDE ELIMINAR UN ENVIO ASOCIADO A UNA REMESA CON MÁS ENVIOS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20433, 
    'EL EXPEDIENTE NO CONTIENE DOCUMENTOS. NO SE PUEDE GENERAR EL INDICE ELECTRONICO SIN NINGUN ELEMENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20434, 
    'NO SE HA PODIDO ELIMINAR LA COMUNICACION. COMPRUEBE QUE EL MENSAJE INDICADO EXISTE.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20435, 
    'EL INTERESADO NO ESTÁ ASOCIADO AL DOCUMENTO INDICADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20436, 
    'LA LONGITUD DE LA CLAVE DE USUARIO DEBE TENER AL MENOS 8 CARÁCTERES.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20437, 
    'LA CLAVE DE USUARIO DEBE TENER AL MENOS UNA LETRA MAYÚSCULA.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20438, 
    'LA CLAVE DE USUARIO DEBE TENER AL MENOS UN NÚMERO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20439, 
    'LA CLAVE DE USUARIO DEBE TENER AL MENOS UNA LETRA.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20440, 
    'EL TIPO DE DOCUMENTO DEBE TENER UN TIPO DE PAGO ASOCIADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20441, 
    'SE HA SUPERADO EL NÚMERO MÁXIMO DE FIRMAS ESPECIFICADAS PARA EL DOCUMENTO CON LA RAZÓN DE INTERÉS DEL INTERESADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20442, 
    'NO SE PUEDE FIRMAR EL DOCUMENTO DEBIDO A QUE SE HA FIRMADO CON OTRO TIPO DE FIRMA PREVIAMENTE. COMPRUEBE QUE LA FIRMA ANTERIOR SEA DE TIPO "N"', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20443, 
    'EL TIPO DE DOCUMENTO AL QUE PERTENECE EL DOCUMENTO A FIRMAR NO SOPORTA LA FIRMA SIN FIRMANTES ASOCIADOS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20444, 
    'EXISTE UN DOCUMENTO PERMITIDO EN EL PROCEDIMIENTO ASOCIADO AL TIPO DE CERTIFICADO SELECCIONADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20445, 
    'EL DOCUMENTO INDICADO NO ES DE TIPO CERTIFICADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20137, 
    'EL TIPO DE TAREA INDICADO NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20138, 
    'NO SE PUEDE INICIAR LA TAREA. LOS DATOS INDICADOS NO SE CORRESPONDEN CON UNA FASE EN LA QUE SE ENCUENTRE EL EXPEDIENTE O EXISTEN RESERVAS POR OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20139, 
    'NO SE PUEDE INICIAR LA TAREA. LA TAREA INDICADA NO EXISTE COMO VÁLIDA EN EL TRAMITADOR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20140, 
    'EL DATO DE CONTACTO INDICADO NO PERTENECE AL INTERESADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20141, 
    'NO EXISTE LA TAREA DEL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20142, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE EL EXPEDIENTE, NO ESTÁ ARCHIVADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20143, 
    'EL ORGANISMO INDICADO NO EXISTE O NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20144, 
    'EL TIPO DE DOCUMENTO INDICADO NO EXISTE O NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20145, 
    'NO EXISTE FIRMA PARA EL DOCUMENTO DEL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20146, 
    'EL COMPONENTE INDICADO NO ES DEL SISTEMA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20147, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE LA TAREA. NO TIENE LOS PERMISOS SUFICIENTES PARA REALIZARLA O LA FASE ACTUAL ESTÁ RESERVADA POR OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20148, 
    'NO SE PUEDE FIRMAR. EL FIRMANTE NO ES EL QUE DEBE FIRMAR. COMPRUEBE EL ORDEN DE LA FIRMA EN CASCADA.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20149, 
    'EL DATO DEL COMPONENTE NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20150, 
    'EL PERFIL DE USUARIO INDICADO NO EXISTE O NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20151, 
    'EL DOCUMENTO NO ES VERSIONABLE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20152, 
    'NO SE PUEDE ELIMINAR EL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20153, 
    'EL PUESTO DE TRABAJO NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20154, 
    'EL EMPLEADO NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20155, 
    'EL PAÍS NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20156, 
    'EL MUNICIPIO NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20157, 
    'LA PROVINCIA NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20158, 
    'EL PUESTO DE TRABAJO NO EXISTE EN EL ORGANISMO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20159, 
    'EL TIPO DE VÍA NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20160, 
    'ERROR GENÉRICO DE BASE DE DATOS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20200, 
    'OCURRIÓ UN ERROR DURANTE LA EXPORTACIÓN DEL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20201, 
    'OCURRIÓ UN ERROR DURANTE LA EXPORTACIÓN DEL PROCEDIMIENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20202, 
    'ERROR AL IMPORTAR PLANTILLAS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20203, 
    'ERROR AL IMPORTAR PERFILES DE USUARIO DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20204, 
    'ERROR AL IMPORTAR VARIABLES DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20205, 
    'ERROR AL IMPORTAR TIPOS DE PÁRRAFOS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20206, 
    'ERROR AL IMPORTAR TIPOS DE ACTOS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20207, 
    'ERROR AL IMPORTAR PARAMETROS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20208, 
    'ERROR AL IMPORTAR BLOQUES DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20209, 
    'ERROR AL IMPORTAR TIPOS DE DOCUMENTOS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20210, 
    'ERROR AL IMPORTAR TAREAS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20211, 
    'ERROR AL IMPORTAR TAREAS EN FASE DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20212, 
    'ERROR AL IMPORTAR CONDICIONES/ACCIONES/AVISOS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20213, 
    'ERROR AL IMPORTAR FASES Y METAFASES DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20214, 
    'ERROR AL IMPORTAR TRANSICIONES DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20215, 
    'ERROR AL IMPORTAR CONDICIONES/ACCIONES/AVISOS POR TRANSICIÓN DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20216, 
    'ERROR AL IMPORTAR PLAZOS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20217, 
    'ERROR AL IMPORTAR LA INFORMACIÓN GRÁFICA DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20218, 
    'ERROR AL IMPORTAR LA DEFINICIÓN DEL PROCEDIMIENTO DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20219, 
    'ERROR AL IMPORTAR, NO SE ENCUENTRA EL TIPO DE INDICACION', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20220, 
    'ERROR AL IMPORTAR, NO SE ENCUENTRA EL TIPO DE PUBLICACION', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20221, 
    'ERROR AL IMPORTAR, NO SE ENCUENTRA EL TIPO DE NORMATIVA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20222, 
    'ERROR AL IMPORTAR, NO SE ENCUENTRA EL AMBITO DE LA LEY', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20223, 
    'ERROR AL IMPORTAR, NO SE ENCUENTRA EL TIPO DE ORGANO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20224, 
    'ERROR AL IMPORTAR, NO EXISTE LA NORMATIVA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20225, 
    'ERROR AL IMPORTAR LAS FICHAS DEL PROCEDIMIENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20226, 
    'ERROR AL IMPORTAR LAS PLANTILLAS DEL PROCEDIMIENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20227, 
    'ERROR AL IMPORTAR, NO SE ENCUENTRA EL TIPO DE ORGANISMO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20228, 
    'LA INFORMACION DE LA FAMILIA O SUBFAMILIA NO ES CORRECTA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20229, 
    'ERROR AL SUBIR FICHEROS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20230, 
    'ERROR AL DESCARGAR FICHEROS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20231, 
    'OCURRIÓ UN ERROR DURANTE LA EXPORTACIÓN DE LOS COMPONENTES DEL SISTEMA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20232, 
    'ERROR DURANTE LA IMPORTACION DE TAREAS EN FASE, YA EXISTE UN DOCUMENTO SIMILAR EN DICHA FASE CON VALIDEZ DIFERENTE AL QUE SE IMPORTA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20233, 
    'ERROR DURANTE LA IMPORTACIÓN, EL XML NO ES VÁLIDO O NO ESTA CERRADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20234, 
    'ERROR AL IMPORTAR RAZONES INTERES DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20235, 
    'ERROR AL IMPORTAR RAZONES INTERES POR PROCEDIMIENTO DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20236, 
    'ERROR AL IMPORTAR RAZONES INTERES POR DOCUMENTO DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20300, 
    'OCURRIÓ UN ERROR DURANTE EL BORRADO DEL PROCEDIMIENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20401, 
    'NO EXISTE EL COMPONENTE EN EL SISTEMA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20402, 
    'EL OBJETO ESPERADO ES NULO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20403, 
    'LA LISTA DE DOCUMENTOS Y DESTINATARIOS ES VACIA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20404, 
    'LA LISTA DE DOCUMENTOS ES VACIA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20405, 
    'LA LISTA DE DESTINATARIOS ES VACIA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20406, 
    'FALTAN ARGUMENTOS EN LA PETICIÓN', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20407, 
    'EL COMPONENTE ESTÁ DUPLICADA, EL SISTEMA NO PUEDE DECIDIR CUAL SEGUIR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20408, 
    'ERROR DE SERVICIO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20409, 
    'EXCEPCIÓN REMOTA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20410, 
    'DATOS INCONGRUENTES EN LA PETICIÓN', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20411, 
    'EL DOCUMENTO NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20412, 
    'EL DOCUMENTO YA ESTÄ NOTIFICADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20413, 
    'ERROR AL REGISTRAR LA NOTIFICACIÓN DEL DOCUMENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20414, 
    'ERROR DESCONOCIDO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20415, 
    'EL DOCUMENTO YA TIENE UN ANEXO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20416, 
    'ERROR AL GRABAR UNA PETICIÓN', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20417, 
    'EL DOCUMENTO ESTÁ VACÍO, FIRMADO O NO PUEDE SER FIRMADO DIGITALMENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20418, 
    'EL DOCUMENTO NO HA SIDO ENVIADO A PORT@FIRMAS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20419, 
    'LA PETICIÓN NO EXISTE O NO ESTÁ ENTREGADA EN EL PORT@FIRMAS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20420, 
    'LA FIRMA DEL DOCUMENTO HA SIDO RECHAZADA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20421, 
    'EL TIPO DE PLANTILLA OFFICE INDICADA NO ES CORRECTA O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20422, 
    'LA CONSULTA DE PLANTILLA MÚLTIPLE INDICADA NO ES CORRECTA O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20423, 
    'SE HA SUPERADO EL NÚMERO MÁXIMO DE INTERESADOS QUE SE PUEDEN ASOCIAR CON LA RAZÓN DE INTERÉS INDICADA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20424, 
    'EXISTEN RAZONES DE INTERÉS ASOCIADAS AL PROCEDIMIENTO. ASEGÚRESE DE QUE LA RAZÓN DE INTERÉS ESTÁ ENTRE LAS DEL PROCEDIMIENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20425, 
    'EXISTEN RAZONES DE INTERÉS ASOCIADAS AL DOCUMENTO. ASEGÚRESE DE QUE LA RAZÓN DE INTERÉS ESTÁ ENTRE LAS DEL DOCUMENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20426, 
    'NO SE PUEDE ASOCIAR EL INTERESADO AL DOCUMENTO CON LA RAZÓN DE INTERÉS, YA QUE NO HAY RAZONES DE INTERËS ASOCIADAS AL DOCUMENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20239, 
    'NO SE PUEDE INSERTAR EL PAGO DE TASA DEBIDO A QUE EL INTERESADO NO ESTA ASOCIADO AL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20995, 
    'LA METAFASE INDICADA NO ES CORRECTA O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20996, 
    'NO EXISTE ASOCIACIÓN ENTRE EL EXPEDIENTE Y EL ORGANISMO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20997, 
    'EL INTERESADO EN EL DOCUMENTO NO TIENE EL CONSENTIMIENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20998, 
    'LA CONSULTA INDICADA NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20999, 
    'EL SISTEMA INDICADO NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20427, 
    'NO SE PUEDE INCORPORAR DOCUMENTO POR REFERENCIA EN ESTADO DE REALIZACIÓN', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20428, 
    'NO SE PUEDE REANUDAR UN DOCUMENTO REFERENCIADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20429, 
    'LOS EXPEDIENTES DE LA LISTA DEBEN PERTENECER AL MISMO TIPO DE EVOLUCIÓN Y ESTAR EN LA MISMA FASE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20237, 
    'ERROR AL IMPORTAR TIPOS DE PAGOS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20238, 
    'NO SE PUEDE ELIMINAR EL EXPEDIENTE DEBIDO A QUE EXISTEN PAGOS DE TASAS ASOCIADAS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20240, 
    'EL PAGO DE TASA DEBE TENER UN EXPEDIENTE ASOCIADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20241, 
    'EL PAGO DE TASA DEBE TENER UN INTERESADO ASOCIADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20161, 
    'NO SE PUEDE DESHACER. EL EXPEDIENTE SE ENCUENTRA EN LA PRIMERA FASE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20242, 
    'EL TIPO DE PAGO NO ESTA ASOCIADO AL PROCEDIMIENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20243, 
    'ERROR AL IMPORTAR CERTIFICADOS DESDE XML', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20001, 
    'EL EXPEDIENTE INDICADO NO ES CORRECTO O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20002, 
    'EL TIPO DE EXPEDIENTE INDICADO NO EXISTE O NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20003, 
    'EL PROCEDIMIENTO INDICADO NO EXISTE O NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20004, 
    'NO SE HA ENCONTRADO NINGUNA VERSIÓN DEL PROCEDIMIENTO QUE ESTÄ EN VIGOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20005, 
    'LA CADUCIDAD INDICADA NO EXISTE PARA EL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20006, 
    'LOS DATOS INDICADOS PARA AMPLIAR/REDUCIR LA CADUCIDAD NO SON CORRECTOS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20007, 
    'EL PARAMETRO EN SUSPENDER/REANUDAR DEL TIPO DE MODIFICACIÓN NO ES VÁLIDO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20008, 
    'LA CADUCIDAD ESTÁ SUSPENDIDA. NO SE PUEDE AMPLIAR/REDUCIR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20009, 
    'LA CADUCIDAD NO ESTÁ SUSPENDIDA. NO SE PUEDE REANUDAR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20010, 
    'LA CADUCIDAD YA ESTÁ SUSPENDIDA. NO SE PUEDE REALIZAR LA SUSPENSION', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20011, 
    'NO SE PUEDE ESTABLECER EL AVISO. NO SE HA INDICADO FECHA DE AVISO O TRANSICION EN EL QUE DEBE PRODUCIRSE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20012, 
    'NO SE PUEDE DEVOLVER LOS EXPEDIENTES CADUCADOS. EL TIPO DE FILTRO INDICADO NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20013, 
    'NO SE PUEDE "ENVIAR A...". LOS DATOS DE TRANSICIÓN INDICADA NO SON CORRECTOS. COMPRUEBE QUE ES UNA TRANSICIÓN POSIBLE A LA QUE SE PUEDE ENVIAR EL EXPEDIENTE.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20014, 
    'NO SE PUEDE TRAMITAR. LA TRANSICION INDICADA NO ESTÁ VALIDA O NO EXISTE EN EL PROCEDIMIENTO INDICADO O NO TIENE LOS PERMISOS DE TRAMITACIÓN ADECUADOS PARA RELIZARLA.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20015, 
    'NO SE PUEDE DESHACER. EL EXPEDIENTE NO SE ENCUENTRA EN LA FASE QUE DESEA DESHACER O NO TIENE PERMISOS PARA HACERLO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20016, 
    'NO SE PUEDE DESHACER. LA SITUACIÓN DEL EXPEDIENTE INDICADA SE ENCUENTRA RESERVADA POR OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20017, 
    'NO SE PUEDE DESHACER. LA FASE TIENE FASES DE UN MÓDULO REUTILIZABLE SIN TRAMITAR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20018, 
    'NO SE PUEDE DESHACER. LA FASE ACTUAL DEL EXPEDIENTE INDICADA SE CORRESPONDE CON UNA DIVISIÓN EN EL PROCEDIMIENTO Y AL MENOS UNA DE ESTAS SE ENCUENTRA RESERVADA POR OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20019, 
    'NO SE PUEDE GENERAR/INCORPORAR. LOS DATOS INDICADOS NO SE CORRESPONDEN CON UNA FASE EN LA QUE SE ENCUENTRE EL EXPEDIENTE O EXISTEN RESERVAS POR OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20020, 
    'NO SE PUEDE MODIFICAR LOS DATOS DE LA FASE. COMPRUEBE QUE EL EXPEDIENTE SE ENCUENTRA EN LA FASE INDICADA, NO ESTÁ RESERVADA POR OTRO USUARIO Y USTED TENGA LOS PERMISOS NECESARIOS PARA MODIFICAR LOS DATOS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20021, 
    'NO SE HAN ENCONTRADO CONDICIONES VÄLIDAS A EVALUAR CON LOS PARÄMETROS INDICADOS. COMPRUEBE QUE EXISTEN CONDICIONES VÁLIDAS ASOCIADAS A LA TRANSICION Y PROCEDIMIENTO INDICADOS Y QUE SE SU COMPROBACIÓN ESTÁ DEFINIDA TAL Y COMO SE HA INDICADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20022, 
    'NO SE HAN ENCONTRADO CONDICIONES VÁLIDAS A EVALUAR CON LOS PARÁMETROS INDICADOS. COMPRUEBE QUE EXISTEN CONDICIONES VÁLIDAS ASOCIADAS A LA TAREA Y PROCEDIMIENTO INDICADOS Y QUE SE SU COMPROBACIÓN ESTÁ DEFINIDA TAL Y COMO SE HA INDICADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20023, 
    'NO SE PUEDE GENERAR. EL DOCUMENTO INDICADO NO EXISTE COMO VÄLIDO EN EL TRAMITADOR O NO TIENE PERMISOS PARA GENERARLO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20028, 
    'NO SE PUEDE FIRMAR EL DOCUMENTO. NO SE HAN PODIDO OBTENER LOS DATOS NECESARIOS PARA LA FIRMA. COMPRUEBE QUE EL FIRMANTE ESTA VIGENTE EN EL SISTEMA Y EL TIPO DE DOCUMENTO PUEDA SER FIRMADO POR EL (YA SEA COMO FIRMANTE PRINCIPAL, DELEGADO O SUSTITUTO).', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20029, 
    'NO SE PUEDE ANULAR LA FIRMA DEL DOCUMENTO. NO SE HAN PODIDO OBTENER LOS DATOS NECESARIOS DE LA FIRMA. COMPRUEBE QUE EL FIRMANTE ESTA VIGENTE EN EL SISTEMA Y EL DOCUMENTO HAYA SIDO FIRMADO POR EL (YA SEA COMO FIRMANTE PRINCIPAL, DELEGADO O SUSTITUTO).', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20449, 
    'PROCEDIMIENTO NO  ADAPTADO AL ENI, EXISTEN DOCUMENTOS O EXPEDIENTES SIN DATOS OBLIGATORIOS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20450, 
    'ES OBLIGATORIO INDICAR EL NÚMERO DE EXPEDIENTE. DEBE CONTENER MENOS DE 13 CARACTERES.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20451, 
    'ES OBLIGATORIO ESTABLECER COMO CONSTANTE GENERAL EL REPOSITORIO HCV ASOCIADO AL SISTEMA TREWA.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20452, 
    'EL ORGANISMO INDICADO NO TIENE CÓDIGO DIR3.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20453, 
    'EL PROCEDIMIENTO NO SE ENCUENTRA ADAPTADO AL ENI.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20454, 
    'EL TIPO DE DOCUMENTO DEBE TENER UN TIPO DOCUMENTAL ENI ASOCIADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20455, 
    'EL PROCEDIMIENTO INDICADO NO TIENE UNA CLASIFICACIÓN ASOCIADA.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20456, 
    'NO SE PUEDE EXPORTAR EL EXPEDIENTE. DEBE TENER AL MENOS UN DOCUMENTO FIRMADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20457, 
    'EL IDENTIFICADOR ENI NO ES UN IDENTIFICADOR NORMALIZADO O NO SE HA PODIDO ENCONTRAR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20458, 
    'ES OBLIGATORIO INDICAR EL ESTADO DE ELABORACIÓN DEL DOCUMENTO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20459, 
    'SI EL ESTADO DE ELABORACIÓN DEL DOCUMENTO ES EE02 Ó EE04 ES OBLIGATORIO INDICAR EL IDENTIFICADOR ENI DEL DOCUMENTO ORIGEN.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20460, 
    'EL EXPEDIENTE INDICADO NO TIENE ASIGNADO ORGANISMO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20461, 
    'EL IDENTIFICADOR ENI ASOCIADO AL DOCUMENTO ORIGEN NO CORRESPONDE CON EL FORMATO ADECUADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20467, 
    'NO SE HA PODIDO CREAR EL EXPEDIENTE. EL PROCEDIMIENTO NO TIENE CONFIGURADO UN CÓDIGO RPA ADECUADO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20468, 
    'NO SE HA PODIDO CREAR EL EXPEDIENTE. YA EXISTE UN EXPEDIENTE CON ESE IDENTIFICADOR ENI.', '-', '-');	
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20024, 
    'NO SE PUEDE INCORPORAR. EL DOCUMENTO INDICADO NO EXISTE COMO VÁLIDO EN EL TRAMITADOR O NO TIENE PERMISOS PARA INCORPORARLO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20025, 
    'EL DOCUMENTO INDICADO NO ES CORRECTO O NO EXISTE EN EL TRAMITADOR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20000, 
    'NO TIENE LOS PERMISOS NECESARIOS PARA REALIZAR ESTA ACCIÓN', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20026, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE EL DOCUMENTO. NO TIENE LOS PERMISOS SUFICIENTES PARA REALIZARLA O LA FASE ACTUAL ESTÄ RESERVADA POR OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20027, 
    'EL PARRAFO INDICADO NO ES CORRECTO O NO EXISTE EN EL TRAMITADOR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20030, 
    'UNO DE LOS FIRMANTES NO EXISTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20031, 
    'EL TIPO DE DOCUMENTO INDICADO NO ES CORRECTO O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20032, 
    'NO SE HA PODIDO ACTUALIZAR EL ESTADO DEL MENSAJE DEL SISTEMA DE INTERCAMBIO DE MENSAJES. COMPRUEBE QUE EL MENSAJE INDICADO EXISTE Y QUE NO PERTENECE A OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20033, 
    'NO SE HA PODIDO ELIMINAR EL MENSAJE DEL SISTEMA DE INTERCAMBIO DE MENSAJES. COMPRUEBE QUE EL MENSAJE INDICADO EXISTE Y QUE NO PERTENECE A OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20034, 
    'NO SE PUEDE INCORPORAR EL DOCUMENTO. EL EXPEDIENTE NO SE ENCUENTRA EN LA FASE INDICADA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20035, 
    'LA TRANSICION NO POSEE COMO FASE INICIAL A LA INDICADA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20036, 
    'NO SE PUEDE DESHACER. EXISTEN TAREAS FINALIZADAS ASOCIADAS A LA SITUACIÓN DEL EXPEDIENTE INDICADA.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20037, 
    'NO SE PUEDE FIRMAR EL DOCUMENTO. EL FIRMANTE INDICADO YA HA FIRMADO EL DOCUMENTO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20038, 
    'EL FIRMANTE NO EXISTE O NO ESTÁ VIGENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20039, 
    'EL TIPO DE FIRMANTE SECUNDARIO NO CONCUERDA CON EL PASADO POR PARÄMETRO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20040, 
    'NO SE PUEDE DESHACER. LA SITUACIÓN DEL EXPEDIENTE INDICADA SE CORRESPONDE CON UNA DIVISIÓN EN EL PROCEDIMIENTO Y AL MENOS UNA DE ÉSTAS NO SE ENCUENTRA EN LA SITUACIÓN ADECUADA O NO TIENE PERMISOS PARA DESHACERLAS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20041, 
    'NO SE PUEDE DESHACER. LA SITUACIÓN INDICADA DEL EXPEDIENTE SE CORRESPONDE CON UNA DIVISIÓN EN EL PROCEDIMIENTO Y AL MENOS UNA DE ÉSTAS TIENE FASES DE UN MÓDULO REUTILIZABLE SIN TRAMITAR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20045, 
    'LA VARIABLE INDICADA NO ES CORRECTA O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20047, 
    'NO SE PERMITE MODIFICAR EL ESTADO DEL DOCUMENTO A "FIRMADO". HA OCURRIDO UN ERROR AL GUARDAR EL FICHERO EN LA BASE DE DATOS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20048, 
    'LOS PARÁMETROS INDICADOS PARA DELEGAR/SUSTITUIR O REVOKAR DELEGACIÓN/SUSTITUCIÓN NO SON CORRECTOS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20049, 
    'NO SE PUEDE REALIZAR LA SUSTITUCIÓN, YA EXISTE ALGÚN SUSTITUTO CON LOS DATOS INDICADOS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20050, 
    'NO SE PUEDE REALIZAR LA DELEGACIÓN, YA EXISTE ALGÚN DELEGADO CON LOS DATOS INDICADOS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20046, 
    'NO SE PERMITE MODIFICAR EL ESTADO DEL DOCUMENTO A "FIRMADO". EL DOCUMENTO NO ESTÁ FIRMADO POR TODOS LOS FIRMANTES DEFINIDOS EN EL SISTEMA.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20051, 
    'NO SE PUEDE REALIZAR LA REVOCACIÓN DE LA DELEGACIÓN/SUSTITUCIÓN. NO SE HAN ENCONTRADO SUSTITUTOS/DELEGADOS VIGENTES CON LOS DATOS INDICADOS', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20052, 
    'NO SE PUEDE DESHACER. LA SITUACIÓN INDICADA DEL EXPEDIENTE SE CORRESPONDE CON UNA DIVISIÓN EN EL PROCEDIMIENTO Y AL MENOS UNA DE ÉSTAS TIENE DOCUMENTOS PENDIENTES DE FIRMA O FIRMADOS ASOCIADOS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20070, 
    'EL PROCEDIMIENTO ORIGEN INDICADO NO EXISTE O NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20071, 
    'EL PROCEDIMIENTO DESTINO INDICADO NO EXISTE O NO ES CORRECTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20072, 
    'EL SISTEMA ORIGEN INDICADO NO EXISTE EN EL DESTINO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20090, 
    'NO SE PUEDE RESERVAR. COMPRUEBE QUE TIENE PERMISOS EN LA/S FASE/S EN LA/S QUE SE ENCUENTRA EL EXPEDIENTE O COMPRUEBE LAS RESERVAS QUE SOBRE LA/S MISMA/S PUEDA TENER OTRO USUARIO.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20091, 
    'LA FASE INDICADA NO ES CORRECTA O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20092, 
    'NO SE PUEDE TRAMITAR, EXISTE ALGUNA TAREA OBLIGATORIA NO TRATADA', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20093, 
    'LA FASE TIENE TRANSICIONES DE UNION PENDIENTES', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20094, 
    'NO SE PUEDE REALIZAR LA ACCIÓN. EXISTEN CONDICIONES OBLIGATORIAS QUE DEBEN CUMPLIRSE.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20095, 
    'EL DOCUMENTO PERMITIDO INDICADO NO ES CORRECTO O NO EXISTE EN EL TRAMITADOR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20096, 
    'NO SE PUEDE ELIMINAR LA RESERVA. COMPRUEBE LA/S FASE/S EN LA/S QUE SE ENCUENTRA EL EXPEDIENTE Y SUS RESERVAS.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20097, 
    'NO SE PUEDE "ENVIAR A...". LA FASE ACTUAL DEL EXPEDIENTE INDICADA NO ES CORRECTA. COMPRUEBE QUE EL EXPEDIENTE SE ENCUENTRA EN DICHA SITUACIÓN.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20098, 
    'LA TRANSICIÓN INDICADA NO ES CORRECTA O NO EXISTE EN EL TRAMITADOR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20099, 
    'NO SE PUEDE TRAMITAR. COMPRUEBE QUE EL EXPEDIENTE SE ENCUENTRE EN LA FASE INDICADA, NO ESTÁ RESERVADA POR OTRO USUARIO O LA FASE INDICADA TENGA FASES DE UN MÓDULO REUTILIZABLE SIN TRAMITAR.', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20100, 
    'NO EXISTE EL INTERESADO, O NO SE HA PODIDO ACTUALIZAR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20101, 
    'NO SE PUEDE ELIMINAR EL INTERESADO, TIENE RELACION CON ALGÚN EXPEDIENTE, O CON OTRO INTERESADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20102, 
    'NO EXISTE LA RAZON DE INTERES', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20103, 
    'NO SE HA PODIDO INSERTAR EL INTERESADO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20104, 
    'NO SE HAN PODIDO INSERTAR LOS DATOS DE CONTACTO, O EL INTERESADO EN EL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20105, 
    'NO EXISTE EL INTERESADO EN EL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20106, 
    'NO HA SIDO POSIBLE ACTUALIZAR EL INTERESADO EN EL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20107, 
    'NO SE PUEDE ELIMINAR O MODIFICAR EL INTERESADO EN EL EXPEDIENTE YA QUE TIENE ASOCIADO UN DOCUMENTO', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20108, 
    'NO SE PUEDE ELIMINAR EL INTERESADO EN EL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20109, 
    'NO SE HA PODIDO ASIGNAR EL DOCUMENTO AL INTERESADO DEL EXPEDIENTE', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20110, 
    'NO SE HA PODIDO ACTUALIZAR O ELIMINAR EL INTERESADO DEL DOCUMENTO YA QUE TIENE NOTIFICACIONES', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20111, 
    'NO EXISTE EL INTERESADO DEL DOCUMENTO, O NO SE HA PODIDO ELIMINAR', '-', '-');
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20112, 
    'NO SE HA PODIDO MODIFICAR EL INTERESADO DEL DOCUMENTO', '-', '-');
	
	
	
	
	
Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20462, 
    'NO EXISTE EL COMPONENTE HCV. ES NECESARIO LA CREACIÓN DEL COMPONENTE HCV Y LA CONFIGURACIÓN DE LA DIRECCIÓN IP.', '-', '-');

Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20463, 
    'ES OBLIGATORIO LA CONFIGURACIÓN DE LA DIRECIÓN IP DEL COMPONENTE HCV.', '-', '-');

Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20464, 
    'NO SE PUEDE REALIZAR LA ACCIÓN SOBRE EL DOCUMENTO. EL TIPO DE DOCUMENTO ESTÁ CONFIGURADO COMO NO EDITABLE POR EL TRAMITADOR.', '-', '-');

Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20465, 
    'NO SE PUEDE REALIZAR LA ACCIÓN DE FIRMA SOBRE EL DOCUMENTO. EL DOCUMENTO PERTENECE A UN TIPO DE DOCUMENTO AUXILIAR.', '-', '-');

Insert into &OWNER..TR_ERRORES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_ERRO, 
    T_MENSAJE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, -20466, 
    'ALGUNA DE LAS VARIABLES INDICADAS NO ES CORRECTA O NO EXISTE EN EL TRAMITADOR.', '-', '-');	
	
	
	
	
COMMIT;
