DEF OWNER="TREWA"

Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'A', 
    'SOCIEDAD ANÓNIMA', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'B', 
    'SOCIEDAD DE RESPONSABILIDAD LIMITADA', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'C', 
    'SOCIEDAD COLECTIVA', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'D', 
    'SOCIEDAD COMANDITARIA', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'E', 
    'COMUNIDAD DE BIENES', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'F', 
    'SOCIEDAD COOPERATIVA', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'G', 
    'ASOCIACIÓN', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'H', 
    'COMUNIDAD DE PROPIETARIOS', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'K', 
    'FORMATO ANTIGUO', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'L', 
    'FORMATO ANTIGUO', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'M', 
    'FORMATO ANTIGUO', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'N', 
    'FORMATO ANTIGUO', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'P', 
    'CORPORACIÓN LOCAL', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'Q', 
    'ORGANISMO AUTÓNOMO', 'S', '-', '-');
Insert into &OWNER..GN_TIPOS_ORGANIZACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_ORGZ, 
    D_TIPO_ORGZ, L_VIGENTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'S', 
    'ORGANO DE LA ADMINISTRACIÓN', 'S', '-', '-');
COMMIT;
