DEF OWNER="TREWA"

Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AL', 
    'ALAMEDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AG', 
    'AGREGADO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AR', 
    'ÁREA, ARRABAL', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AV', 
    'AVENIDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AY', 
    'ARROYO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'BJ', 
    'BAJADA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'BO', 
    'BARRIO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'BR', 
    'BARRANCO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CG', 
    'COLEGIO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CH', 
    'CHALET', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CJ', 
    'CALLEJA, CALLEJ', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CL', 
    'CALLE', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CM', 
    'CAMINO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CN', 
    'CONJUNTO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CO', 
    'COLONIA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CR', 
    'CARRETERA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CS', 
    'CASERÍO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CT', 
    'CUESTA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'DP', 
    'DIPUTACIÓN', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'DS', 
    'DISEMINADOS', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'ED', 
    'EDIFICIOS', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'RU', 
    'RUA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'ER', 
    'EXTRARRADIO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'ES', 
    'ESCALINATA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'EP', 
    'EXPLANADA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'FC', 
    'FERROCARRIL', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'GL', 
    'GLORIETA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'GR', 
    'GRUPO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'GV', 
    'GRAN VIA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'HT', 
    'HUERTA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'JR', 
    'JARDINES', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'LD', 
    'LADO, LADERA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'LG', 
    'LUGAR', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'MC', 
    'MERCADO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'ML', 
    'MUELLE', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'MN', 
    'MUNICIPIO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'MS', 
    'MASIA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'MT', 
    'MONTE', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'MZ', 
    'MANZANA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PB', 
    'POBLADO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PD', 
    'PARTIDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PG', 
    'POLIGONO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PJ', 
    'PASAJE,PASADIZO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PQ', 
    'PARROQUIA,PARQUE', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PR', 
    'PROLONGACION', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PS', 
    'PASEO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PT', 
    'PUENTE', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PZ', 
    'PLAZA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'QT', 
    'QUINTA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'RB', 
    'RAMBLA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'RC', 
    'RINCON', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'RD', 
    'RONDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'RM', 
    'RAMAL', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'RP', 
    'RAMPA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'RR', 
    'RIERA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'SA', 
    'SALIDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'SD', 
    'SENDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'SL', 
    'SOLAR', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TN', 
    'TERRENOS', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TO', 
    'TORRENTE', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TR', 
    'TRAVESIA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'UR', 
    'URBANIZACION', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AU', 
    'AUTOPISTA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AC', 
    'ARCO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CA', 
    'CAÑADA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CI', 
    'CINTURON', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CP', 
    'CAMPO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CU', 
    'CONJUNTO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'DE', 
    'DETRAS', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'FN', 
    'FINCA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PL', 
    'POLÍGONO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PP', 
    'PLAN PARCIAL', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PM', 
    'PÁRAMO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'SN', 
    'SALÓN', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'ST', 
    'SITIO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'VR', 
    'VEREDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'EM', 
    'EXTRAMUROS', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PE', 
    'PARAJE', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AP', 
    'APARTAMENTO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'BL', 
    'BLOQUE', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CD', 
    'CORREGIDOR', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'EN', 
    'ENTRADA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PA', 
    'PARCELA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PU', 
    'PUERTA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'SB', 
    'SUBIDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'VI', 
    'VÍA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'VP', 
    'VÍA PÚBLICA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'DI', 
    'DISEMINADO', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'PY', 
    'PLAYA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'RS', 
    'RESIDENCIAL', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'SU', 
    'SUBIDA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'ZN', 
    'ZONA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'CC', 
    'CENT. COMERCIAL', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'VT', 
    'VENTA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'BD', 
    'BARRIADA', 'N', NULL, '-', '-');
Insert into &OWNER..GN_TIPOS_VIA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_TIPO_VIA, 
    D_TIPO_VIA, L_OBSOLETO, C_NIWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'AD', 
    'ALDEA', 'N', NULL, '-', '-');
COMMIT;
