DEF OWNER="TREWA"

Insert into &OWNER..GN_CONSTANTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_CONSTANTE, 
    D_CONSTANTE, V_CONSTANTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TRAPI', 
    'VERSIÓN DE LA API', '2.5.1', '-', '-');
Insert into &OWNER..GN_CONSTANTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_CONSTANTE, 
    D_CONSTANTE, V_CONSTANTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TRSTMA', 
    'SISTEMA POR DEFECTO', 'TREWA', '-', '-');
Insert into &OWNER..GN_CONSTANTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_CONSTANTE, 
    D_CONSTANTE, V_CONSTANTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TRVERS', 
    'VERSIÓN TREW@', '2.5.1', '-', '-');
Insert into &OWNER..GN_CONSTANTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_CONSTANTE, 
    D_CONSTANTE, V_CONSTANTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TRUSUPROP', 
    'USUARIO PROPIETARIO DE LOS OBJETOS DE TREW@', 'TREWA', '-', '-');
Insert into &OWNER..GN_CONSTANTES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, C_CONSTANTE, 
    D_CONSTANTE, V_CONSTANTE, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'FECHA', 
    'Fecha de la aplicación', SYSDATE, '-', '-');
COMMIT;
