DEF OWNER="TREWA"

Insert into &OWNER..TR_PERFILES_USUARIOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_PEUS, 
    STMA_X_STMA, C_NOMBRE, D_DESCRIPCION, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    1, 'TR_ADMINISTRADOR', 'PERFIL DE USUARIO "ADMINISTRADOR" PARA USUARIOS NO ORACLE', '-', '-');
Insert into &OWNER..TR_PERFILES_USUARIOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_PEUS, 
    STMA_X_STMA, C_NOMBRE, D_DESCRIPCION, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    1, 'TR_R_USUARIO', 'PERFIL DE USUARIO "NORMAL" PARA USUARIOS NO ORACLE', '-', '-');
Insert into &OWNER..TR_PERFILES_USUARIOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_PEUS, 
    STMA_X_STMA, C_NOMBRE, D_DESCRIPCION, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    1, 'TR_R_ADMINISTRADOR', 'ADMINISTRADOR', '-', '-');
COMMIT;