DEF OWNER="TREWA"

Insert into &OWNER..TR_USUARIOS_X_PERFILES_USUARIO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, USUA_C_USUARIO, 
    PEUS_X_PEUS, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TREWA', 
    1, '-', '-');
Insert into &OWNER..TR_USUARIOS_X_PERFILES_USUARIO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, USUA_C_USUARIO, 
    PEUS_X_PEUS, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TREWA', 
    2, '-', '-');
Insert into &OWNER..TR_USUARIOS_X_PERFILES_USUARIO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, USUA_C_USUARIO, 
    PEUS_X_PEUS, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 'TREWA', 
    3, '-', '-');
COMMIT;
