DEF OWNER="TREWA"


Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    1, 'CAB_ORGANO', 'CABECERA "ÓRGANO_GESTOR"', '$$ORGANO_GESTOR$$', 'I', 
    NULL, 'NEGRIT', 'NORMAL', 'A', 'N', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    1, 'PIE_DIRECCION', 'PIE DIRECCIÓN ORGANO_GESTOR', '$$DIRECCION_OG$$', 'D', 
    NULL, 'NORMAL', 'NORMAL', 'P', 'N', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    1, 'TIT_PRAL', 'TÍTULO PRINCIPAL (JUSTIFICADO + NEGRITA)', NULL, 'J', 
    NULL, 'NEGRIT', 'NE-SU', 'C', 'N', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    1, 'TXT_NORMAL', 'TEXTO NORMAL (JUSTIFICADO + NORMAL)', NULL, 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 5, 
    1, 'TIT_SECUNDARIO', 'TÍTULO SECUNDARIO -"ANTECEDENTES DE HECHO", "HECHOS", ETC.- (CENTRANDO + NEGRITA)', NULL, 'C', 
    NULL, 'NEGRIT', 'NORMAL', 'C', 'N', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 6, 
    1, 'TXT_ETIQ_LARGA', 'TEXTO CON ETIQUETA LARGA DE PALABRAS: "PRIMERO", "SEGUNDO", ETC. (JUSTIFICADO + TEXTO NORMAL + ETIQUETA NEGRITA)', NULL, 'J', 
    'ETIQ1', 'NORMAL', 'NEGRIT', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 7, 
    1, 'TXT_SANG_LARGO', 'TEXTO SIN ETIQUETA SANGRADO LARGO (JUSTIFICADO + NORMAL)', NULL, 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 8, 
    1, 'NRI_NUM_FECHA', 'NÚMERO Y FECHA DE COMUNICACIÓN INTERIOR', '<ESCRIBA Nº>##$$FECHA_NRI$$', 'I', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 9, 
    1, 'NRI_ASUNTO', 'ASUNTO DE LA COMUNICACIÓN INTERIOR', '<ESCRIBA EL ASUNTO>', 'I', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 10, 
    1, 'NRI_REMIT_DEST', 'REMITENTE Y DESTINATARIO DE LA COMUNICACIÓN INTERIOR', '$$REMITENTE_NRI$$##$$DESTINATARIO_NRI$$', 'I', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 11, 
    1, 'SALTO_PAGINA', 'INSERTA SALTO DE PÁGINA', '*SALTO DE PAGINA*', 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'N', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 12, 
    1, 'TXT_ETIQ_CORTA', 'TEXTO CON ETIQUETA CORTA DE PALABRAS: "1.-", "*", "a)", ETC. (JUSTIFICADO + TEXTO NORMAL + ETIQUETA NEGRITA)', NULL, 'J', 
    'ETIQ2', 'NORMAL', 'NEGRIT', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 13, 
    1, 'TXT_SANG_CORTO', 'TEXTO SIN ETIQUETA SANGRADO CORTO (JUSTIFICADO + NORMAL)', NULL, 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 14, 
    1, 'COLUMNA_IZQ', 'TEXTO EN COLUMNA IZQUIERDA (IZQUIERDA + NORMAL )', NULL, 'I', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 15, 
    1, 'COLUMNA_CENTRAL', 'TEXTO EN COLUMNA CENTRAL (IZQUIERDA + NORMAL)', NULL, 'I', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 16, 
    1, 'COLUMNA_DER', 'TEXTO EN COLUMNA DERECHA (IZQUIERDA + NORMAL)', NULL, 'I', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 17, 
    1, 'REFERENCIA_IZQ', 'TEXTO "REFERENCIA" IZQUIERDA (IZQUIERDA + NORMAL)', NULL, 'I', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 18, 
    1, 'REFERENCIA_DER', 'TEXTO "REFERENCIA" DERECHA (DERECHA + NORMAL)', NULL, 'D', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 19, 
    1, 'TXT_DILIGENCIA', 'TEXTO NORMAL DESPUES DE LA FIRMA', NULL, 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 20, 
    1, 'TXT_DILIG_SALTO', 'TEXTO NORMAL CON SALTO DE PAGINA DESPUES DE LA FIRMA', NULL, 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 21, 
    1, 'IMAGEN_IZQ', 'TEXTO NORMAL (JUSTIFICADO + NORMAL)', NULL, 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 22, 
    1, 'IMAGEN_DER', 'TEXTO NORMAL (JUSTIFICADO + NORMAL)', NULL, 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
Insert into &OWNER..TR_TIPOS_PARRAFOS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIPA, 
    STMA_X_STMA, C_ABREVIATURA, D_DESCRIPCION, T_CONTENIDO, V_ALINEACION, 
    T_ETIQUETA, V_ESTILO, V_ESTILO_ETIQ, V_UBICACION, L_EDITABLE, 
    B_IMAGEN, T_FORMATO, T_NOMB_FICHERO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 23, 
    1, 'TABLA', 'TIPO DE PÁRRAFO PARA TABLAS', ',,,;,,;', 'J', 
    NULL, 'NORMAL', 'NORMAL', 'C', 'S', 
    NULL, NULL, NULL, '-', '-');
COMMIT;
