DEF OWNER="TREWA"

Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'AUTO', 'AUTO', 'N', 'AUTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    'CIRCULAR', 'CIRCULAR', 'N', 'CIRCULAR', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    'CONVENIO', 'CONVENIO', 'N', 'CONVENIO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    'DECRETO', 'DECRETO', 'N', 'DECRETO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 5, 
    'DEC. PRES.', 'DECRETO DEL PRESIDENTE', 'N', 'DECRETO DEL PRESIDENTE', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 6, 
    'ACUERDO', 'ACUERDO', 'N', 'ACUERDO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 7, 
    'INSTRUCC.', 'INSTRUCCIÓN', 'N', 'INSTRUCCIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 8, 
    'LEY', 'LEY', 'N', 'LEY', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 9, 
    'LEY ORG.', 'LEY ORGÁNICA', 'N', 'LEY ORGÁNICA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 10, 
    'NORMA', 'NORMA', 'N', 'NORMA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 11, 
    'ORDEN', 'ORDEN', 'N', 'ORDEN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 12, 
    'ORDENANZA', 'ORDENANZA', 'N', 'ORDENANZA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 13, 
    'PROVIDENC.', 'PROVIDENCIA', 'N', 'PROVIDENCIA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 14, 
    'REAL DEC.', 'REAL DECRETO', 'N', 'REAL DECRETO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 15, 
    'R. DEC.LEY', 'REAL DECRETO-LEY', 'N', 'REAL DECRETO-LEY', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 17, 
    'SENTENCIA', 'SENTENCIA', 'N', 'SENTENCIA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 19, 
    'ACTA', 'ACTA', 'N', 'ACTA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 20, 
    'ADDENDUM', 'ADDENDUM', 'N', 'ADDENDUM', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 21, 
    'ADICIÓN', 'ADICIÓN', 'N', 'ADICIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 22, 
    'AJUSTES', 'AJUSTES', 'N', 'AJUSTES', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 23, 
    'ANEJO', 'ANEJO', 'N', 'ANEJO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 24, 
    'ANUNCIO', 'ANUNCIO', 'N', 'ANUNCIO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 25, 
    'ARBITRAJE', 'ARBITRAJE', 'N', 'ARBITRAJE', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 26, 
    'ARREGLO', 'ARREGLO', 'N', 'ARREGLO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 27, 
    'AVISO', 'AVISO', 'N', 'AVISO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 28, 
    'BANDO', 'BANDO', 'N', 'BANDO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 29, 
    'BASE', 'BASE', 'N', 'BASE', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 30, 
    'C. CARTAS', 'CANJE DE CARTAS', 'N', 'CANJE DE CARTAS', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 31, 
    'C. NOTAS', 'CANJE DE NOTAS', 'N', 'CANJE DE NOTAS', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 32, 
    'CARTA', 'CARTA', 'N', 'CARTA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 33, 
    'CITACIÓN', 'CITACIÓN', 'N', 'CITACIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 34, 
    'CÓDIGO', 'CÓDIGO', 'N', 'CÓDIGO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 35, 
    'COMUNIC.', 'COMUNICACIÓN', 'N', 'COMUNICACIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 36, 
    'COMUNICADO', 'COMUNICADO', 'N', 'COMUNICADO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 37, 
    'CONCIERTO', 'CONCIERTO', 'N', 'CONCIERTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 38, 
    'CONCORDATO', 'CONCORDATO', 'N', 'CONCORDATO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 39, 
    'CONCURSO', 'CONCURSO', 'N', 'CONCURSO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 40, 
    'CONDICIÓN', 'CONDICIÓN', 'N', 'CONDICIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 41, 
    'CONSTITUC.', 'CONSTITUCIÓN', 'N', 'CONSTITUCIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 42, 
    'CONSULTA', 'CONSULTA', 'N', 'CONSULTA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 43, 
    'CONTRATO', 'CONTRATO', 'N', 'CONTRATO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 45, 
    'CONVOCAT.', 'CONVOCATORIA', 'N', 'CONVOCATORIA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 46, 
    'DAHIR', 'DAHIR', 'N', 'DAHIR', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 47, 
    'DECISIÓN', 'DECISIÓN', 'N', 'DECISIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 48, 
    'DECLARAC.', 'DECLARACIÓN', 'N', 'DECLARACIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 49, 
    'D.FOR.LEG.', 'DECRETO FORAL LEGISLATIVO', 'N', 'DECRETO FORAL LEGISLATIVO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 50, 
    'DEC. LEG.', 'DECRETO LEGISLATIVO', 'N', 'DECRETO LEGISLATIVO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 51, 
    'DEC. LEY', 'DECRETO-LEY', 'N', 'DECRETO-LEY', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 52, 
    'DENUNCIA', 'DENUNCIA', 'N', 'DENUNCIA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 53, 
    'DIRECTIVA', 'DIRECTIVA', 'N', 'DIRECTIVA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 54, 
    'DIRECTRIC.', 'DIRECTRICES', 'N', 'DIRECTRICES', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 55, 
    'DISPOSIC.', 'DISPOSICIÓN', 'N', 'DISPOSICIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 56, 
    'DOCUMENTO', 'DOCUMENTO', 'N', 'DOCUMENTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 57, 
    'EDICTO', 'EDICTO', 'N', 'EDICTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 58, 
    'ENMIENDA', 'ENMIENDA', 'N', 'ENMIENDA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 59, 
    'ESTATUTO', 'ESTATUTO', 'N', 'ESTATUTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 60, 
    'INFORME', 'INFORME', 'N', 'INFORME', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 61, 
    'INST. CIRC', 'INSTRUCCIÓN CIRCULAR', 'N', 'INSTRUCCIÓN CIRCULAR', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 62, 
    'INSTRUMEN.', 'INSTRUMENTO', 'N', 'INSTRUMENTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 63, 
    'LAUDO', 'LAUDO', 'N', 'LAUDO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 64, 
    'LEY FORAL', 'LEY FORAL', 'N', 'LEY FORAL', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 66, 
    'MANDATO', 'MANDATO', 'N', 'MANDATO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 67, 
    'MEMORÁND.', 'MEMORÁNDUM', 'N', 'MEMORÁNDUM', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 68, 
    'MOCIÓN', 'MOCIÓN', 'N', 'MOCIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 69, 
    'MODIFICAC.', 'MODIFICACIÓN', 'N', 'MODIFICACIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 70, 
    'MOTUPROPIO', 'MOTUPROPIO', 'N', 'MOTUPROPIO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 71, 
    'NORMA FOR.', 'NORMA FORAL', 'N', 'NORMA FORAL', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 72, 
    'NOTA', 'NOTA', 'N', 'NOTA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 73, 
    'OFICIO', 'OFICIO', 'N', 'OFICIO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 74, 
    'OF.CIRCUL.', 'OFICIO CIRCULAR', 'N', 'OFICIO CIRCULAR', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 75, 
    'O. CIRCUL.', 'ORDEN CIRCULAR', 'N', 'ORDEN CIRCULAR', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 76, 
    'ORGANIGR.', 'ORGANIGRAMA', 'N', 'ORGANIGRAMA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 77, 
    'OTROS', 'OTROS', 'N', 'OTROS', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 78, 
    'PACTO', 'PACTO', 'N', 'PACTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 79, 
    'PLAN', 'PLAN', 'N', 'PLAN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 81, 
    'PROGRAMA', 'PROGRAMA', 'N', 'PROGRAMA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 82, 
    'PROTOCOLO', 'PROTOCOLO', 'N', 'PROTOCOLO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 83, 
    'REAL ORD.', 'REAL ORDEN', 'N', 'REAL ORDEN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 84, 
    'PROY.CONV.', 'PROYECTO DE CONVENIO', 'N', 'PROYECTO DE CONVENIO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 85, 
    'R.DEC.LEG.', 'REAL DECRETO LEGISLATIVO', 'N', 'REAL DECRETO LEGISLATIVO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 86, 
    'R.ORD.CIR.', 'REAL ORDEN CIRCULAR', 'N', 'REAL ORDEN CIRCULAR', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 87, 
    'RECOMENDAC', 'RECOMENDACIÓN', 'N', 'RECOMENDACIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 88, 
    'REFORMA', 'REFORMA', 'N', 'REFORMA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 89, 
    'REGLAMENT.', 'REGLAMENTACIÓN', 'N', 'REGLAMENTACIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 90, 
    'REGLAMENTO', 'REGLAMENTO', 'N', 'REGLAMENTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 91, 
    'RELACIÓN', 'RELACIÓN', 'N', 'RELACIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 92, 
    'RES. CIRC.', 'RESOLUCIÓN-CIRCULAR', 'N', 'RESOLUCIÓN-CIRCULAR', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 93, 
    'REVISIÓN', 'REVISIÓN', 'N', 'REVISIÓN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 94, 
    'TEXTO', 'TEXTO', 'N', 'TEXTO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 95, 
    'TRATADO', 'TRATADO', 'N', 'TRATADO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 18, 
    'ACLARACION', 'ACLARACION', 'N', 'ACLARACION', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 16, 
    'RESOLUCION', 'RESOLUCION', 'N', 'RESOLUCION', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 44, 
    'CONVENCION', 'CONVENCION', 'N', 'CONVENCION', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 65, 
    'LEY ORGAN.', 'LEY ORGANICA', 'N', 'LEY ORGANICA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_NORMATIVA
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TINO, 
    C_ABREVIATURA, D_TIPO_NORMA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 80, 
    'PREVENCION', 'PREVENCION', 'N', 'PREVENCION', '-', 
    '-');
COMMIT;
