DEF OWNER="TREWA"

Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 40, 
    3, 'OO_AUTO_GUARDA', 'false', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 41, 
    3, 'OO_MODO_APERTURA_APP', 'edit', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 42, 
    3, 'OO_SERVLET_WEBDAV', 'false', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 43, 
    5, 'CERTIFICADOCLIENTE', 'certificadocliente', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 44, 
    5, 'CODIGO_SERVICIO', '2943', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 45, 
    5, 'IDCOMPONENTE', '1', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 46, 
    5, 'PKCS12.ARCHIVO', '/home/geades/notificaciones/KeystoreNotifica.p12', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 47, 
    5, 'PKCS12.PASS', '123456', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 48, 
    5, 'PKCS12.PASS.CLASEPWD', 'as', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 49, 
    5, 'PKCS12.PASS.METODO', 'propiedad', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 50, 
    5, 'XML_LOG', '/home/geades/notificaciones/mcneLog4jConfig.xml', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    1, 'PROTOCOLO', 'http', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    1, 'PUERTO', '9090', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    1, 'RUTA', '/trewaws/services/trewa?wsdl', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    1, 'TIMEOUT', '20000', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 5, 
    1, 'ROL', 'Administrador', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 6, 
    2, 'PROTOCOLO', 'http', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 7, 
    2, 'PUERTO', '9090', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 8, 
    2, 'RUTA', '/wardAService/services/wardA?wsdl', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 9, 
    2, 'TIMEOUT', '20000', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 10, 
    2, 'ROL', 'Administrador', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 11, 
    3, 'OO_MARCA_VARIABLE', '$$', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 12, 
    3, 'OO_SEPARADOR_COLUMNA', ',', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 13, 
    3, 'OO_SEPARADOR_FILA', ';', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 14, 
    3, 'OO_PREFIJO_TABLA', 'TAB_', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 15, 
    3, 'OO_PREFIJO_IMAGEN', 'IMG_', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 16, 
    3, 'OO_TIPO_DESTINO', 'StarOffice XML (Writer)', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 17, 
    4, 'PUERTO', '5050', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 18, 
    4, 'PROTOCOLO', 'http', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 19, 
    4, 'RUTA', '/avisador/services/ArServicioWS?wsdl', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 20, 
    5, 'PROTOCOLO', 'https', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 21, 
    5, 'PUERTO', '443', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 22, 
    5, 'RUTA', 'jboss-net/services/ServicioWEBSN', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 23, 
    6, 'PROTOCOLO', 'http', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 24, 
    6, 'PUERTO', '8080', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 25, 
    6, 'RUTA', '/pfirmav3/services/PfServicioWS?wsdl', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 26, 
    7, 'CODIFICADORAS', '/justiciayadministracionpublica/.../agrupadores/processes/codificadoras.jpd?WSDL', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 27, 
    7, 'DOCUMENTOS', '/justiciayadministracionpublica/.../agrupadores/processes/documentos.jpd?WSDL', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 28, 
    7, 'EXPEDIENTES', '/justiciayadministracionpublica/.../agrupadores/processes/expedientes.jpd?WSDL', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 29, 
    7, 'INTERESADOS', '/justiciayadministracionpublica/.../agrupadores/processes/interesados.jpd?WSDL', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 30, 
    7, 'PROCEDIMIENTOS', '/justiciayadministracionpublica/.../agrupadores/processes/procedimientos.jpd?WSDL', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 31, 
    7, 'PROTOCOLO', 'http', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 32, 
    7, 'ROL', 'Administrador', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 33, 
    7, 'TIMEOUT', '20000', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 34, 
    8, 'PROTOCOLO', 'http', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 35, 
    8, 'PUERTO', '8081', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 36, 
    8, 'ROL', 'Administrador', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 37, 
    8, 'RUTA', '/wardAService/services/wardAService?wsdl', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 38, 
    8, 'TIMEOUT', '20000', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 39, 
    6, 'TIPO_FIRMA', 'TF04', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 51, 
    10, 'clase', 'NumeradorPT', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 53, 
    10, 'paquete', 'es.juntadeandalucia.plataforma.numeradorPT', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 55, 
    9, 'PROTOCOLO', 'https', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 57, 
    9, 'RUTA', '/afirmaws/services/', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 58, 
    9, 'ID_APLICACION', 'CHAP.PTWANDA', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 59, 
    9, 'FIRMANTE', 'default', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 60, 
    9, 'MODO', 'UsernameToken', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 61, 
    9, 'PASSWORDTYPE', 'A', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 62, 
    11, 'PROTOCOLO', 'HTTP', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 63, 
    11, 'PUERTO', '8000', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 64, 
    11, 'RUTA_ENIDOC_CLIENT', '/hcv/rest/eni/', '-', '-');
Insert into &OWNER..TR_DATOS_COMPONENTE
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_DATC, 
    COMP_X_COMP, C_ATRIBUTO, T_VALOR, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 65, 
    11, 'TURA_VERIFICACION', '/hcv/', '-', '-');	
COMMIT;
