DEF OWNER="TREWA"

Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'AVI', 'video/avi', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    'CSS', 'text/css', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    'CSV', 'text/csv', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    'DOCX', 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 5, 
    'GML', 'application/gml+xml', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 6, 
    'GZIP', 'application/x-gzip', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 7, 
    'HTML', 'text/html', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 8, 
    'JPEG', 'image/jpeg', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 9, 
    'JPG', 'image/jpeg', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 10, 
    'MHT', 'message/rfc822', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 11, 
    'MHTML', 'message/rfc822', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 12, 
    'MP3', 'audio/mpeg3', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 13, 
    'MP4', 'video/mp4', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 14, 
    'MPEG', 'audio/mpeg', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 15, 
    'ODG', 'application/vnd.oasis.opendocument.graphics', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 16, 
    'ODP', 'application/vnd.oasis.opendocument.presentation', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 17, 
    'ODS', 'application/vnd.oasis.opendocument.spreadsheet', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 18, 
    'ODT', 'application/vnd.oasis.opendocument.text', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 19, 
    'OGA', 'application/ogg', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 20, 
    'OGG', 'application/ogg', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 21, 
    'PDF', 'application/pdf', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 22, 
    'PNG', 'image/png', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 23, 
    'PPTX', 'application/vnd.openxmlformats-officedocument.presentationml.presentation', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 24, 
    'RTF', 'application/rtf', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 25, 
    'SVG', 'image/svg+xml', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 26, 
    'TIFF', 'image/tiff', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 27, 
    'TXT', 'text/plain', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 28, 
    'WEBM', 'video/webm', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 29, 
    'WFS', 'application/octet-stream', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 30, 
    'WMS', 'application/x-ms-wms', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 31, 
    'XLSX', 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 32, 
    'XML', 'text/xml', '-', '-');
Insert into &OWNER..TR_FORMATODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_FOEN, 
    C_FORMATO_ENI, C_FORMATO_TREWA, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 33, 
    'ZIP', 'application/zip', '-', '-');
COMMIT;
