DEF OWNER="TREWA"

Insert into &OWNER..TR_NUMERADORES
   (X_NUM, ANYO, SIS_ORIGEN, NUMERADOR, CREADO, 
    F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, MODIFICADO_API)
 Values
   (1, '2018', 'TREWA', 1, USER, 
    SYSDATE, USER, SYSDATE, '-', '-');
Insert into &OWNER..TR_NUMERADORES
   (X_NUM, ANYO, SIS_ORIGEN, NUMERADOR, CREADO, 
    F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, MODIFICADO_API)
 Values
   (2, '2017', 'TREWA', 1, USER, 
    SYSDATE, USER, SYSDATE, '-', '-');
COMMIT;