DEF OWNER="TREWA"

Insert into &OWNER..TR_PARAMETROS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_PARA, 
    STMA_X_STMA, C_NOMBRE, D_DESCRIPCION, V_TIPO, N_TAMANIO, 
    CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    1, 'P_FASE', 'IDENTIFICADOR DE LA FASE', 'N', 10, 
    '-', '-');
Insert into &OWNER..TR_PARAMETROS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_PARA, 
    STMA_X_STMA, C_NOMBRE, D_DESCRIPCION, V_TIPO, N_TAMANIO, 
    CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    1, 'P_EXP', 'NÚMERO DEL EXPEDIENTE', 'N', 10, 
    '-', '-');
Insert into &OWNER..TR_PARAMETROS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_PARA, 
    STMA_X_STMA, C_NOMBRE, D_DESCRIPCION, V_TIPO, N_TAMANIO, 
    CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    1, 'P_TIPO_DOC', 'TIPO DE DOCUMENTO', 'N', 10, 
    '-', '-');
Insert into &OWNER..TR_PARAMETROS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_PARA, 
    STMA_X_STMA, C_NOMBRE, D_DESCRIPCION, V_TIPO, N_TAMANIO, 
    CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    1, 'P_REF_DOC', 'IDENTIFICADOR DEL DOCUMENTO PERMITIDO', 'N', 10, 
    '-', '-');
COMMIT;
