DEF OWNER="TREWA"

Insert into &OWNER..TR_PLANTILLAS
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_PLAN, 
    STMA_X_STMA, C_NOMBRE, D_DESCRIPCION, T_NOMB_INFORME, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    1, 'TR_DOC_GENERAL', 'PLANTILLA GENERAL PARA LA GENERACIÓN DE DOCUMENTOS OFICIOS, INFORMES, RESOLUCIONES, PROPUESTAS, ETC...', 'DOC_GENERAL.xml', '-', 
    '-');
COMMIT;
