DEF OWNER="TREWA"

Insert into &OWNER..TR_RAZONES_INTERES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_RAIN, 
    C_ABREVIATURA, D_RAZON_INTERES, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    'REPR', 'REPRESENTANTE', 'N', NULL, '-', 
    '-');
Insert into &OWNER..TR_RAZONES_INTERES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_RAIN, 
    C_ABREVIATURA, D_RAZON_INTERES, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'SOLICITANT', 'SOLICITANTE', 'N', NULL, '-', 
    '-');
Insert into &OWNER..TR_RAZONES_INTERES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_RAIN, 
    C_ABREVIATURA, D_RAZON_INTERES, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    'ENC', 'SUPERVISOR', 'N', NULL, '-', 
    '-');
Insert into &OWNER..TR_RAZONES_INTERES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_RAIN, 
    C_ABREVIATURA, D_RAZON_INTERES, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    'REPLEGAL', 'REPRESENTANTE LEGAL', 'N', NULL, '-', 
    '-');
COMMIT;
