DEF OWNER="TREWA"

Insert into &OWNER..TR_TEXTOS_DISPOSICIONES
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TEDI, 
    T_TEXTO, V_TIPO, CREADO_API, MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'DECRETO', 'D', '-', '-');
COMMIT;
