DEF OWNER="TREWA"

Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 1, 'TD01', 'Resolución', '1', 
    'DECISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 2, 'TD02', 'Acuerdo', '1', 
    'DECISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 3, 'TD03', 'Contrato', '1', 
    'DECISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 4, 'TD04', 'Convenio', '1', 
    'DECISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 5, 'TD05', 'Declaración', '1', 
    'DECISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 6, 'TD06', 'Comunicación', '1', 
    'TRANSMISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 7, 'TD07', 'Notificación', '1', 
    'TRANSMISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 8, 'TD08', 'Publicación', '1', 
    'TRANSMISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 9, 'TD09', 'Acuse de recibo', '1', 
    'TRANSMISIÓN');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 10, 'TD10', 'Acta', '1', 
    'CONSTANCIA');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 11, 'TD11', 'Certificado', '1', 
    'CONSTANCIA');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 12, 'TD12', 'Diligencia', '1', 
    'CONSTANCIA');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 13, 'TD13', 'Informe', '1', 
    'JUICIO');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 14, 'TD14', 'Solicitud', '0', 
    'CIUDADANO');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 15, 'TD15', 'Denuncia', '0', 
    'CIUDADANO');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 16, 'TD16', 'Alegación', '0', 
    'CIUDADANO');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 17, 'TD17', 'Recursos', '0', 
    'CIUDADANO');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 18, 'TD18', 'Comunicación ciudadano', '0', 
    'CIUDADANO');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 19, 'TD19', 'Factura', '0', 
    'CIUDADANO');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 20, 'TD20', 'Otros incautados', '0', 
    'CIUDADANO');
Insert into &OWNER..TR_TIPODOC_ENI
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, CREADO_API, 
    MODIFICADO_API, X_TDEN, C_TIPODOC_ENI, D_TIPODOC_ENI, V_ORIGEN, 
    V_GRUPO_DOC)
 Values
   (USER, SYSDATE, USER, SYSDATE, '-', 
    '-', 21, 'TD99', 'Otros (Origen Administración)', '1', 
    'OTROS');
COMMIT;
