DEF OWNER="TREWA"

Insert into &OWNER..TR_TIPOS_CONTACTO
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TCON, 
    C_ABREVIATURA, D_TIPO_CONTACTO, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    'Repre_ante', 'REPRESENTANTE', 'N', NULL, '-', 
    '-');
COMMIT;
 