DEF OWNER="TREWA"

Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 1, 
    'OBJ', 'OBJETO', 'N', 'OBJ', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 2, 
    'REQ', 'REQUISITOS PREVIOS', 'N', 'REQ', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 3, 
    'DOC', 'DOCUMENTACIÓN REQUERIDA', 'N', 'DOC', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 4, 
    'PSO', 'PLAZO DE SOLICITUD', 'N', 'PSO', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 5, 
    'PMN', 'PLAZO MÁXIMO DE NOTIFICACIÓN', 'N', 'PMN', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 6, 
    'ESA', 'EFECTOS DEL SILENCIO ADMINISTRATIVO', 'N', 'ESA', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 7, 
    'NOT', 'NOTAS', 'N', 'NOT', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 8, 
    'ORG', 'ÓRGANO COMPETENTE EN LA MATERIA', 'N', 'ORG', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 9, 
    'TOR', 'TIPO DE ÓRGANO', 'N', 'TOR', '-', 
    '-');
Insert into &OWNER..TR_TIPOS_INDICACION
   (CREADO, F_CREACION, MODIFICADO, F_MODIFICA, X_TIIN, 
    C_ABREVIATURA, D_TIPO_INDICA, L_OBSOLETO, C_NIWA, CREADO_API, 
    MODIFICADO_API)
 Values
   (USER, SYSDATE, USER, SYSDATE, 10, 
    'NOR', 'NORMATIVA', 'N', NULL, '-', 
    '-');
COMMIT;
